[pytest]
# Test discovery rules
# Tell pytest which files, classes and functions should be recognized as tests
python_files = test_*.py        # Any file starting with test_ will be treated as test files
python_classes = Test*          # Any class starting with "Test" will be recognized as a test class
python_functions = test_*       # Any function starting with test_ will be treated as a test function

# Pytest output and behavior
addopts =
    -v                          # Verbose mode which shows detailed test results
    --tb=short                  # Shorter traceback for easier reading when tests fail
    --strict-markers            # Enforce that test markers must be registered below


# Test directory
# Tells pytest where to look for tests. So for me it's the "tests" folder
testpaths = tests               

# Custom test markers
# Allows me to label tests (Like: @pytest.mark.unit)
markers =
    unit: Unit tests for small, isolated functions.
    api: API endpoint tests (e.g., FastAPI routes).
    integration: Tests involving the combination of components.
    slow: Tests expected to take longer to execute.
