[pytest]
# Test discovery rules
# Tell pytest which files, classes and functions should be recognized as tests
# Any file starting with test will be treated as test files
python_files = test*.py
# Any class starting with "Test" will be recognized as a test class      
python_classes = Test*
# Any function starting with test_ will be treated as a test function         
python_functions = test_*     

# Pytest output and behavior
addopts =
    -v                          
    --tb=short                  
    --strict-markers            


# Test directory
# Tells pytest where to look for tests. So for me it's the "tests" folder
testpaths = tests             

# Custom test markers
# Allows me to label tests (Like: @pytest.mark.unit)
markers =
    unit: Unit tests for small, isolated functions.
    api: API endpoint tests (e.g., FastAPI routes).
    integration: Tests involving the combination of components.
    slow: Tests expected to take longer to execute.
